version: '3.1'

services:

  postgres_goMKdb:
    container_name: postgres_goMKdb
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
